#! /bin/csh -fe
if ($#argv < 2)then
  echo "ERS_ESA_PRI: read an ERS PRI tape processed by an ESA PAF 03-Aug-98"
  echo "usage: ERS_ESA_PRI <orbit> <device> " 
  echo "       <orbit>   orbit identifier (example: orbit number)"
  echo "       <device>  EXABYTE tape device (no rewind); example: /dev/rmt/0mn"
  exit
endif

set EXABYTE = $2
rm -f $1.par.out

echo "Reading ESA ERS PRI tape..."

echo "reading CEOS volume directory file: $1.vdf"
dd bs=360 if=$EXABYTE of=$1.vdf

echo "reading CEOS SAR leader file: $1.ldr"
dd bs=16384 if=$EXABYTE of=$1.ldr

echo "reading PRI image file: $1.pri" 
dd bs=19612 if=$EXABYTE of=$1.pri

echo "reading CEOS null volume directory file: $1.nvdf"
dd bs=360 if=$EXABYTE of=$1.nvdf

echo "ERS_ESA_PRI completed"

 
