#! /bin/csh -f
if ($#argv < 2)then
  echo "READ annotated ERS raw data tape produced by CCRS (Canadian Centre for Remote Sensing)"
  echo "usage: ERS_CCRS_RAW <orbit> <device>"
  echo "       orbit   orbit number"
  echo "       device  EXABYTE tape device name; example: /dev/rmt/0mn" 
  exit
endif

set EXABYTE = $2
setenv TAPE $EXABYTE
echo "Reading ERS annotated raw data tape produced by CCRS..."
mt rew

echo "Reading CEOS volume directory file: $1.vdf"
dd bs=360 if=$EXABYTE of=$1.vdf

echo "Reading CEOS leader file: $1.ldr"
dd bs=16384 if=$EXABYTE of=$1.ldr

echo "Reading ESA raw data file: $1.raw.1"
dd bs=12060 if=$EXABYTE of=$1.raw.1
echo "rewinding tape..."
mt offl

echo "LOAD TAPE #2, then hit return..."
set name=$<
echo "mt fsf 1"
mt fsf 1
echo "Reading ESA raw data file: $1.raw.2"
dd bs=12060 if=$EXABYTE of=$1.raw.2
echo "rewinding tape..."
mt offl

echo "LOAD TAPE #3, then hit return..."
set name=$<
echo "mt fsf 1"
mt fsf 1
echo "Reading ESA raw data file: $1.raw.3"
dd bs=12060 if=$EXABYTE of=$1.raw.3
echo "rewinding tape..."
mt offl

echo "ERS_CCRS_RAW completed"
